[pc]
rt_tester_dir = /home/taranev/work_repos/rt/rt-tester
arduino_port = /dev/ttyACM0
trace_prometheus_url = http://127.0.0.1:9091
trace_prometheus_addr = 127.0.0.1:9091
trace_grafana_addr = 127.0.0.1:3001

[supervisor]
ssh = root@10.42.0.211
board = repkapi4
iface = end0
rt_supervisor_dir = /root/rt-supervisor
supervisor_bin = /root/rt-supervisor/Build/src/alt-rt-supervisor
runtime_wrapper = /root/beremiz-runtime/supervised-raw-plc/start_runtime.sh
erpc_url = ERPC://10.42.0.211:3000

[controller]
ssh = root@10.43.0.2
ssh_jump = root@10.42.0.211
board = rockpi4
iface = end0
rt_supervisor_dir = /root/rt-supervisor
controller_bin = /root/rt-supervisor/Build/src/controller-emu

[measurement]
params = /home/taranev/work_repos/rt/rt-tester/src/pc-receiver/measurement-supervised-smoke.conf
groups = 2
measurements_per_group = 1500
interval_us = 5000
receiver_timeout_sec = 120
